In [1]:
import pandas as pd

In [2]:
sr1 = pd.Series([10,20,30,40,50])
sr1

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
dict1 = {
    'col1': pd.Series([10,20,30,40,50]),
    'col2': ('a','b','c','d','e')}
df1 = pd.DataFrame(dict1)
df1

   col1 col2
0    10    a
1    20    b
2    30    c
3    40    d
4    50    e

In [4]:
df1 = pd.DataFrame({'id': [1,2,3,4,5], 'stat_marks': [90,94,95,98,92]})
df2 = pd.DataFrame({'id': [3,4,5,6,7], 'ml_marks': [89,92,91,89,96]})
df2

   id  ml_marks
0   3        89
1   4        92
2   5        91
3   6        89
4   7        96

In [5]:
df1.merge(df2, on = 'id', how = 'inner')  # (how = inner) == inner join

   id  stat_marks  ml_marks
0   3          95        89
1   4          98        92
2   5          92        91

In [6]:
df1.merge(df2, on = 'id', how = 'left')  # (how = left) == left join

   id  stat_marks  ml_marks
0   1          90       NaN
1   2          94       NaN
2   3          95      89.0
3   4          98      92.0
4   5          92      91.0

In [7]:
df1.merge(df2, on = 'id', how = 'right')  # (how = right) == Right join

   id  stat_marks  ml_marks
0   3        95.0        89
1   4        98.0        92
2   5        92.0        91
3   6         NaN        89
4   7         NaN        96

In [8]:
df1.merge(df2, on = 'id', how = 'outer')  # (how = outer) == full join

   id  stat_marks  ml_marks
0   1        90.0       NaN
1   2        94.0       NaN
2   3        95.0      89.0
3   4        98.0      92.0
4   5        92.0      91.0
5   6         NaN      89.0
6   7         NaN      96.0

In [9]:
pwd  # to check file location

'D:\\MLfiles\\practice-self\\Pandas'

In [10]:
df1 = pd.read_csv('Auto.csv')  # to upload file as my file name is Auto.csv
df1.head()  # To check the first 5 row of data of shared file

,mpg,cylinders,displacement,Horse Power,weight,acceleration,year,origin,name
0,18.0,8.0,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8.0,350.0,165,3693,11.5,70,1,buick skylark 320
2,NaN,8.0,318.0,150,3436,11.0,70,1,plymouth satellite
3,NaN,8.0,NaN,150,3433,12.0,70,1,amc rebel sst
4,NaN,8.0,NaN,140,3449,10.5,70,1,ford torino

In [11]:
df1.dtypes

mpg             float64
cylinders       float64
displacement    float64
Horse Power      object
weight            int64
acceleration    float64
year              int64
origin            int64
name             object
dtype: object

In [12]:
df1.describe()

,mpg,cylinders,displacement,weight,acceleration,year,origin
count,392.000000,394.000000,392.000000,397.000000,397.000000,397.000000,397.000000
mean,23.611735,5.439086,191.080357,2970.261965,15.555668,75.994962,1.574307
std,7.827466,1.693452,102.452019,847.904119,2.749995,3.690005,0.802549
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,100.750000,2223.000000,13.800000,73.000000,1.000000
50%,23.000000,4.000000,145.500000,2800.000000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,260.000000,3609.000000,17.100000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [13]:
df1['Horse Power'] = pd.to_numeric(df1['Horse Power'], errors = 'coerce')

In [14]:
df1['mpg'] = df1['mpg'].fillna(df1['mpg'].mean())

In [15]:
df1['mpg'] = df1['mpg'].fillna(23.611734693877548) # 
df1['mpg'].isnull().sum()

np.int64(0)

In [16]:
df1.drop('name',axis = 1, inplace = True)

In [17]:
df1.loc[1:7,'mpg':'acceleration']  # slicing with no n-1

         mpg  cylinders  displacement  Horse Power  weight  acceleration
1  15.000000        8.0         350.0        165.0    3693          11.5
2  23.611735        8.0         318.0        150.0    3436          11.0
3  23.611735        8.0           NaN        150.0    3433          12.0
4  23.611735        8.0           NaN        140.0    3449          10.5
5  23.611735        8.0           NaN        198.0    4341          10.0
6  23.611735        8.0           NaN        220.0    4354           9.0
7  14.000000        8.0           NaN        215.0    4312           8.5

In [18]:
df1.iloc[1:7,'mpg':'acceleration']  # slicing with no n-1

TypeError: cannot do positional indexing on Index with these indexers [mpg] of type str

In [ ]:
cond2 = (df1['mpg']> 35) & (df1['origin'] ==  2)
df1[cond2]